# Tensors


In [1]:
import torch

In [ ]:
distances = torch.tensor([[3.0],[3.4]])
print(distances.shape) ##Here are 2 samples that is the batch size and 1 feature per sample  


torch.Size([2, 1])


# Mixing Type

In [5]:
distances1 = torch.tensor([1.2,1.3,1.4],dtype=torch.float32)
distances2 = torch.tensor([1,2,3],dtype=torch.int64)
mixed_tensor = distances1+distances2
print(f"type:{mixed_tensor.dtype}")


type:torch.float32


In [11]:
#Creating tensors

##1.From List

my_distances=[[1.2,2.3]]
tensor_from_list = torch.tensor(my_distances)
print(tensor_from_list.shape)
##2.From numpy array
import numpy as np
numpy_array = np.array([1,2,2])
tensor_from_numpy=torch.from_numpy(numpy_array)
print(tensor_from_numpy.shape)

torch.Size([1, 2])
torch.Size([3])


In [15]:
zeros = torch.zeros(3,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
ones = torch.ones(3,3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [20]:
rand = torch.rand(3,3)
print(rand)

tensor([[0.6826, 0.4428, 0.7438],
        [0.6275, 0.3071, 0.6634],
        [0.0039, 0.2806, 0.8015]])


In [21]:
distance= torch.tensor(23)
print(distance.shape)

torch.Size([])


In [33]:
with_batch=distance.unsqueeze(0)# will add batch dim
print(with_batch)
print(with_batch.shape)

tensor([23])
torch.Size([1])


In [32]:
ready_for_model=with_batch.unsqueeze(1)
print(ready_for_model)
print(ready_for_model.shape)

tensor([[23]])
torch.Size([1, 1])


In [28]:
squeezed=ready_for_model.squeeze()
print(squeezed)


tensor(23)


In [35]:
## indexing and shaping
predictions = torch.tensor([[1.2],[3.4]],dtype= torch.int16)

#get the first prediction
print(predictions[0])

#get the first 2
print(predictions[:2])

#use .item() to get the py num
print(predictions[0].item())

tensor([1], dtype=torch.int16)
tensor([[1],
        [3]], dtype=torch.int16)
1


In [39]:
data = torch.tensor([[1,2,3],
                    [3,4,5]],dtype=torch.int16)

print(data[:,2])



tensor([3, 5], dtype=torch.int16)
